# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('seconddomain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seconddomain',
            name='agt_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent', to_field='agt_id', verbose_name='Agent \u7f16\u53f7'),
            preserve_default=False,
        ),
    ]
