# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('ipinfo', '0001_initial'),
        ('seconddomain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameserver_port', models.IntegerField(default=53, help_text='\u8bf7\u8f93\u5165\u57df\u540d\u670d\u52a1\u5668\u7684\u7aef\u53e3', verbose_name='NS PORT')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent', to_field='agentid', verbose_name='Agent\u7f16\u53f7')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seconddomain.SecondDomain', to_field='domain', verbose_name='\u57df\u540d')),
                ('namereverse_ip', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipinfo_reverse_ip', to='ipinfo.IPinfo', to_field='reverse_ip', verbose_name='\u53cd\u5411IP')),
                ('nameserver_ip', models.ForeignKey(help_text='\u8bf7\u8f93\u5165\u57df\u540d\u670d\u52a1\u5668\u7684IP', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='ipinfo_ip', to='ipinfo.IPinfo', to_field='ipaddress', verbose_name='NS IP')),
            ],
            options={
                'db_table': 'server',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('namereverse_ip', 'agentid')]),
        ),
    ]
