# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='namereverse_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipinfo_reverse_ip', to='ipinfo.IPinfo', to_field='reverse_ip', verbose_name='\u53cd\u5411IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='nameserver_ip',
            field=models.ForeignKey(blank=True, help_text='\u8bf7\u8f93\u5165\u57df\u540d\u670d\u52a1\u5668\u7684IP', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipinfo_ip', to='ipinfo.IPinfo', to_field='ipaddress', verbose_name='NS IP'),
        ),
    ]
