# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='\u65f6\u95f4\u6233')),
                ('state', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u544a\u8b66'), (2, '\u9519\u8bef')], default=0, verbose_name='\u72b6\u6001')),
                ('agent_version', models.CharField(max_length=5, verbose_name='Agent\u7248\u672c')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('message', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4fe1\u606f\u4fdd\u7559')),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent', to_field='agentid', verbose_name='Agent ID')),
            ],
            options={
                'db_table': 'heartbeat',
                'managed': True,
            },
        ),
    ]
