# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srv',
            name='srv_port',
            field=models.IntegerField(default=0, verbose_name='\u7aef\u53e3'),
        ),
    ]
