# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('permission', models.IntegerField(choices=[(0, '\u666e\u901a\u7528\u6237'), (1, '\u7ba1\u7406\u5458'), (2, '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=0, verbose_name='\u6743\u9650')),
                ('email', models.EmailField(max_length=30, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('qq', models.CharField(max_length=11, verbose_name='QQ\u53f7')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'dnsuser',
            },
        ),
    ]
