# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsuser',
            name='username',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
