# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alias', '0002_remove_alias_ip_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='ip_choice',
            field=models.IntegerField(choices=[(0, '\u5355\u4e2aIP'), (1, 'IP\u5730\u5740\u6bb5')], default=0, verbose_name='IP\u9009\u62e9'),
        ),
    ]
