# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolv',
            name='resolv_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipinfo.IPinfo', to_field='ipaddress', verbose_name='IP'),
        ),
    ]
