# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, unique=True, verbose_name='\u57df\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=30, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=30, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u57df\u540d',
                'db_table': 'second_domain',
                'managed': True,
                'verbose_name_plural': '\u57df\u540d',
            },
        ),
    ]
