# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, unique=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('create_user', models.CharField(max_length=30)),
                ('update_user', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': '\u57df\u540d',
                'db_table': 'second_domain',
                'managed': True,
                'verbose_name_plural': '\u57df\u540d',
            },
        ),
    ]
