# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('seconddomain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45, unique=True, verbose_name='\u522b\u540d')),
                ('ttl', models.SmallIntegerField(default=600, verbose_name='\u751f\u547d\u5468\u671f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=30, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=30, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('agentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent', to_field='agentid', verbose_name='Agent\u7f16\u53f7')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seconddomain.SecondDomain', to_field='domain', verbose_name='\u4e8c\u7ea7\u57df\u540d')),
            ],
            options={
                'verbose_name': '\u522b\u540d',
                'db_table': 'cname',
                'managed': True,
                'verbose_name_plural': '\u522b\u540d',
            },
        ),
    ]
