# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('seconddomain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=45, unique=True)),
                ('ttl', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('create_user', models.CharField(max_length=30)),
                ('update_user', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('area_name', models.ForeignKey(db_column='area_name', on_delete=django.db.models.deletion.DO_NOTHING, to='area.Area')),
                ('domain', models.ForeignKey(db_column='domain', on_delete=django.db.models.deletion.DO_NOTHING, to='seconddomain.SecondDomain')),
            ],
            options={
                'verbose_name': '\u522b\u540d',
                'db_table': 'cname',
                'managed': True,
                'verbose_name_plural': '\u522b\u540d',
            },
        ),
    ]
