# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seconddomain', '0001_initial'),
        ('cname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cname',
            name='cname',
            field=models.CharField(max_length=45, verbose_name='\u522b\u540d'),
        ),
        migrations.AlterUniqueTogether(
            name='cname',
            unique_together=set([('cname', 'domain')]),
        ),
    ]
