# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('seconddomain', '0001_initial'),
        ('mx', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mx',
            unique_together=set([('mxDomain', 'domain', 'agentid')]),
        ),
    ]
