# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cname', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cname',
            options={'verbose_name': '\u522b\u540d', 'verbose_name_plural': '\u522b\u540d'},
        ),
        migrations.AlterField(
            model_name='cname',
            name='agt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent', to_field='agt_id', verbose_name='Agent\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='cname',
            name='cname',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u522b\u540d'),
        ),
    ]
