# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domain_name', models.CharField(blank=True, max_length=45, null=True)),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('agentip', models.IntegerField(blank=True, db_column='agentIp', null=True)),
                ('agentversion', models.CharField(blank=True, db_column='agentVersion', max_length=45, null=True)),
                ('agentstatu', models.CharField(blank=True, db_column='agentStatu', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('oldip', models.CharField(blank=True, db_column='oldIp', max_length=45, null=True)),
                ('startipendip', models.IntegerField(blank=True, db_column='startIpEndIp', null=True)),
                ('newip', models.IntegerField(blank=True, db_column='newIp', null=True)),
                ('mask', models.CharField(blank=True, max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'alias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(blank=True, db_column='areaName', max_length=45, null=True)),
                ('responsible', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('cnamename', models.CharField(blank=True, db_column='cnameName', max_length=45, null=True)),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('ttl', models.IntegerField(blank=True, db_column='TTL', null=True)),
                ('create_time', models.CharField(blank=True, max_length=45, null=True)),
                ('update_time', models.CharField(blank=True, max_length=45, null=True)),
                ('update_user', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computername', models.CharField(blank=True, db_column='computerName', max_length=45, null=True)),
                ('responsible', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'computer_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoaminName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(blank=True, null=True)),
                ('multilevel', models.CharField(blank=True, max_length=45, null=True)),
                ('fulldomainname', models.CharField(blank=True, db_column='fullDomainName', max_length=45, null=True)),
                ('analytictype', models.CharField(blank=True, db_column='analyticType', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('createuser', models.CharField(blank=True, db_column='createUser', max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'doamin_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FDomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('createuser', models.CharField(blank=True, db_column='createUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'f_domain_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('ttl', models.CharField(blank=True, db_column='TTL', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=30, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'host-record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField(blank=True, null=True)),
                ('computerid', models.IntegerField(blank=True, db_column='computerId', null=True)),
                ('remark', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ipinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('mailname', models.CharField(blank=True, db_column='mailName', max_length=45, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'mx',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ptr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resolv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('ip', models.IntegerField(blank=True, db_column='IP', null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'resolv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SDomainName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('fulldomainname', models.CharField(blank=True, db_column='fullDomainName', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('createuser', models.CharField(blank=True, db_column='createUser', max_length=30, null=True)),
            ],
            options={
                'db_table': 's_domain_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domain_name', models.CharField(blank=True, max_length=45, null=True)),
                ('reverseip', models.IntegerField(blank=True, db_column='reverseIp', null=True)),
                ('nsip', models.IntegerField(blank=True, db_column='nsIp', null=True)),
                ('nsport', models.CharField(blank=True, db_column='nsPort', max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'servere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Srv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('serveraddr', models.CharField(blank=True, db_column='serverAddr', max_length=45, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=45, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('updateuser', models.CharField(blank=True, db_column='updateUser', max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'srv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaid', models.IntegerField()),
                ('domainname', models.CharField(blank=True, db_column='domainName', max_length=45, null=True)),
                ('text', models.CharField(blank=True, max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('update_user', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'txt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_column='userName', max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('permission', models.CharField(blank=True, max_length=45, null=True)),
                ('createtime', models.DateTimeField(blank=True, db_column='createTime', null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
