# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_ip', models.GenericIPAddressField(verbose_name='Agent_IP')),
                ('agent_version', models.CharField(blank=True, max_length=45, null=True, verbose_name='Agent\u7248\u672c')),
                ('agent_statu', models.IntegerField(choices=[(1, '\u542f\u7528\u4e2d'), (2, '\u505c\u7528\u4e2d'), (3, '\u6682\u505c')], help_text='Agent\u72b6\u6001', verbose_name='Agent\u72b6\u6001')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ip', models.GenericIPAddressField(verbose_name='\u539fIP')),
                ('start_ip', models.GenericIPAddressField(verbose_name='\u8d77\u59cbIP')),
                ('end_ip', models.GenericIPAddressField(verbose_name='\u7ed3\u675fIP')),
                ('new_ip', models.GenericIPAddressField(verbose_name='\u65b0IP')),
                ('mask', models.CharField(max_length=45, verbose_name='\u63a9\u7801')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'alias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=45, verbose_name='\u533a\u57df\u7b80\u79f0')),
                ('area_name', models.CharField(max_length=45, verbose_name='\u533a\u57df')),
                ('responsible', models.CharField(max_length=45, verbose_name='\u8d1f\u8d23\u4eba')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u533a\u57df',
                'db_table': 'area',
                'managed': True,
                'verbose_name_plural': '\u533a\u57df',
            },
        ),
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(max_length=45, verbose_name='\u522b\u540d\u5730\u5740')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('ttl', models.IntegerField(blank=True, null=True, verbose_name='\u751f\u5b58\u5468\u671f')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'cname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComputerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=45, verbose_name='\u673a\u623f')),
                ('responsible', models.CharField(max_length=45, verbose_name='\u8d1f\u8d23\u4eba')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'computer_room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doamin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(blank=True, null=True, verbose_name='\u6b21\u7ea7\u57df\u540d')),
                ('multilevel', models.IntegerField(choices=[(2, '\u4e8c\u7ea7\u57df\u540d'), (3, '\u4e09\u7ea7\u57df\u540d'), (4, '\u56db\u7ea7\u57df\u540d')], verbose_name='\u5c42\u7ea7')),
                ('full_domain', models.CharField(max_length=45, verbose_name='\u5b8c\u6574\u57df\u540d')),
                ('analytic_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u89e3\u6790\u7c7b\u578b')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'doamin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u9876\u7ea7\u57df\u540d')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'f_domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('ttl', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u751f\u5b58\u5468\u671f')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'host-record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ipinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('cname', models.IntegerField(verbose_name='\u522b\u540d')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remark', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'ipinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=45, verbose_name='\u672c\u5730IP')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'local',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('mail_domain', models.CharField(max_length=45, verbose_name='Mx\u8bb0\u5f55\u503c')),
                ('preference', models.IntegerField(verbose_name='\u4f18\u5148\u7ea7')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'mx',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ptr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'ptr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resolv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8 ')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'resolv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(verbose_name='\u9876\u7ea7\u57df\u540dId')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('full_domain', models.CharField(max_length=45, verbose_name='\u5b8c\u6574\u57df\u540d')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('doamin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dns.Doamin')),
                ('f_domain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dns.FDomain')),
            ],
            options={
                'db_table': 's_domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('server_ptr', models.CharField(max_length=32, verbose_name='\u670d\u52a1\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'servere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Srv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('server_domain', models.CharField(max_length=45, verbose_name='\u670d\u52a1\u5730\u5740')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('priority', models.IntegerField(verbose_name='\u4f18\u5148\u7ea7')),
                ('weight', models.IntegerField(verbose_name='\u6743\u91cd')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'srv',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('mail_domain', models.CharField(max_length=45, verbose_name='mx\u8bb0\u5f55\u503c')),
                ('preference', models.IntegerField(verbose_name='\u4f18\u5148\u7ea7')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'txt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=45, verbose_name='\u5bc6\u7801')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('permission', models.IntegerField(choices=[(1, '\u666e\u901a\u7528\u6237'), (2, '\u7ba1\u7406\u5458'), (3, '\u521b\u5efa\u4eba')], verbose_name='\u6743\u9650')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='computerroom',
            name='ipinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dns.Ipinfo'),
        ),
        migrations.AddField(
            model_name='alias',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='agent',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Area', verbose_name='\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaid', to='dns.Area', verbose_name='\u533a\u57df'),
        ),
    ]
