# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(verbose_name='\u5bc6\u7801'),
        ),
    ]
