# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('update_user', models.CharField(max_length=45, verbose_name='\u4fee\u6539\u8005')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaid', to='area.Area', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
    ]
