# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addr_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipinfo.IPinfo', to_field='ipaddress', verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='address',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seconddomain.SecondDomain', to_field='domain', verbose_name='\u57df\u540d'),
        ),
    ]
