# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliasId', models.IntegerField()),
                ('oldip', models.GenericIPAddressField()),
                ('startipEndip', models.CharField(max_length=200)),
                ('newip', models.GenericIPAddressField()),
                ('ipmask', models.GenericIPAddressField()),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('createTime', models.DateField(verbose_name=b'2017-10-30')),
                ('upTime', models.DateField(verbose_name=b'2017-10-30')),
                ('updateUser', models.CharField(default='now user', max_length=30)),
            ],
            options={
                'db_table': 'alias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaname', models.CharField(blank=True, db_column='areaName', max_length=45, null=True)),
                ('responsible', models.CharField(blank=True, max_length=45, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnameId', models.IntegerField()),
                ('cn', models.CharField(max_length=100)),
                ('dns', models.CharField(max_length=100)),
                ('ttl', models.IntegerField(default=10)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('createTime', models.DateField(verbose_name=b'2017-10-30')),
                ('upTime', models.DateField(verbose_name=b'2017-10-30')),
                ('updateUser', models.CharField(default='now user', max_length=30)),
                ('cnameForeign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area')),
            ],
            options={
                'db_table': 'cname',
            },
        ),
        migrations.AddField(
            model_name='alias',
            name='aliasForeign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area'),
        ),
    ]
