# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u57df\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agt_ip', models.GenericIPAddressField(verbose_name='\u4ee3\u7406IP')),
                ('agt_version', models.IntegerField(default=1, verbose_name='\u7248\u672c')),
                ('agt_states', models.IntegerField(choices=[(0, 'running'), (1, 'down'), (2, 'pause'), (3, 'unknown')], default=1, verbose_name='\u8fd0\u884c\u72b6\u6001')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upTime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('createUser', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('updateUser', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_ip', models.GenericIPAddressField(verbose_name='\u539fIP')),
                ('start_ip', models.GenericIPAddressField(verbose_name='\u8d77\u59cbIP')),
                ('end_ip', models.GenericIPAddressField(verbose_name='\u7ed3\u675fIP')),
                ('new_ip', models.GenericIPAddressField(verbose_name='\u65b0IP')),
                ('ipmask', models.GenericIPAddressField(verbose_name='\u63a9\u7801')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'alias',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bf7\u586b\u5199\u533a\u57df\u7684\u82f1\u6587\u7f29\u5199', max_length=10, unique=True, verbose_name='\u533a\u57df\u7b80\u79f0')),
                ('fullname', models.CharField(max_length=45, unique=True, verbose_name='\u533a\u57df\u540d')),
                ('machine_name', models.CharField(max_length=45, unique=True, verbose_name='\u673a\u623f\u540d')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Cname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, unique=True, verbose_name='\u522b\u540d')),
                ('ttl', models.IntegerField(default=10, verbose_name='TTL')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'cname',
            },
        ),
        migrations.CreateModel(
            name='ComOjbect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('current_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='DNSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('permission', models.IntegerField(choices=[(0, '\u8d85\u7ea7\u7ba1\u7406\u5458'), (1, '\u7ba1\u7406\u5458'), (2, '\u666e\u901a\u7528\u6237')], default=2, verbose_name='\u6743\u9650')),
                ('email', models.EmailField(max_length=30, verbose_name='\u90ae\u7bb1\u5730\u5740')),
                ('qq', models.CharField(max_length=11, verbose_name='QQ\u53f7')),
                ('phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7')),
                ('current_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'dnsuser',
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='\u65f6\u95f4\u6233')),
                ('state', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u4e22\u5931')], default=0, verbose_name='\u72b6\u6001')),
                ('agent_ip', models.GenericIPAddressField(verbose_name='Agent IP')),
                ('message', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4fe1\u606f\u4fdd\u7559')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.IntegerField(default=600, verbose_name='TTL')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='IPinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'ip',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, verbose_name='\u672c\u5730\u57df\u540d')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
                ('host_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.IPinfo', to_field='ipaddress', verbose_name='\u4e3b\u673a')),
            ],
            options={
                'db_table': 'local',
            },
        ),
        migrations.CreateModel(
            name='Loginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='\u65f6\u95f4\u6233')),
                ('state', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u9519\u8bef'), (2, 'unknown')], default=0, verbose_name='\u72b6\u6001')),
                ('agent_ip', models.GenericIPAddressField(verbose_name='Agent IP')),
                ('message', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u4fe1\u606f\u4fdd\u7559')),
            ],
            options={
                'db_table': 'Loginfo',
            },
        ),
        migrations.CreateModel(
            name='Mx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mxDomain', models.EmailField(max_length=45, verbose_name='\u670d\u52a1\u5730\u5740')),
                ('priority', models.IntegerField(default=10, verbose_name='\u6743\u91cd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'mx',
            },
        ),
        migrations.CreateModel(
            name='Ptr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'ptr',
            },
        ),
        migrations.CreateModel(
            name='Resolv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolv_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('resolv_port', models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
            ],
            options={
                'db_table': 'resolv',
            },
        ),
        migrations.CreateModel(
            name='SecondDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, unique=True, verbose_name='\u6b21\u7ea7\u57df\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'second_domain',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_ip', models.GenericIPAddressField(verbose_name='\u53cd\u5411IP')),
                ('nameserver_ip', models.GenericIPAddressField(help_text='\u8bf7\u8f93\u5165\u57df\u540d\u670d\u52a1\u5668\u7684', verbose_name='NS IP')),
                ('nameserver_port', models.IntegerField(default=53, help_text='\u8bf7\u8f93\u5165\u57df\u540d\u670d\u52a1\u5668\u7684\u7aef\u53e3', verbose_name='NS PORT')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d')),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='Srv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_domain', models.CharField(max_length=45, verbose_name='\u670d\u52a1\u5730\u5740')),
                ('srv_port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('priority', models.IntegerField(default=10, verbose_name='\u4f18\u5148\u7ea7')),
                ('weight', models.IntegerField(default=10, verbose_name='\u6743\u91cd')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d')),
            ],
            options={
                'db_table': 'srv',
            },
        ),
        migrations.CreateModel(
            name='TopDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=45, unique=True, verbose_name='\u9876\u7ea7\u57df\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('delete_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'topdomain',
            },
        ),
        migrations.CreateModel(
            name='Txt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=45, verbose_name='TEXT')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d')),
            ],
            options={
                'db_table': 'txt',
            },
        ),
        migrations.AddField(
            model_name='ptr',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='ptr',
            name='ptr_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.IPinfo', to_field='ipaddress', verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='mx',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='host',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.IPinfo', to_field='ipaddress', verbose_name='IP\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='cname',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.SecondDomain', to_field='domain', verbose_name='\u57df\u540d'),
        ),
        migrations.AddField(
            model_name='area',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.DNSUser', to_field='username', verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='alias',
            name='area_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='agent',
            name='area_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='address',
            name='addr_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.IPinfo', to_field='ipaddress', verbose_name='IP \u5730\u5740'),
        ),
        migrations.AddField(
            model_name='address',
            name='area_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsmasq.Area', to_field='name', verbose_name='\u533a\u57df'),
        ),
    ]
