# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnsuser',
            old_name='current_time',
            new_name='create_time',
        ),
        migrations.AlterField(
            model_name='dnsuser',
            name='permission',
            field=models.IntegerField(choices=[(0, '\u666e\u901a\u7528\u6237'), (1, '\u7ba1\u7406\u5458'), (2, '\u8d85\u7ea7\u7ba1\u7406\u5458')], default=2, verbose_name='\u6743\u9650'),
        ),
    ]
