# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0002_auto_20171111_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='time',
            field=models.IntegerField(unique=True, verbose_name='\u65f6\u95f4\u6233'),
        ),
        migrations.AlterField(
            model_name='loginfo',
            name='time',
            field=models.IntegerField(unique=True, verbose_name='\u65f6\u95f4\u6233'),
        ),
    ]
