# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnsuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u8bf7\u586b\u5199\u533a\u57df\u7684\u82f1\u6587\u7f29\u5199', max_length=10, unique=True, verbose_name='\u533a\u57df\u7b80\u79f0')),
                ('fullname', models.CharField(max_length=45, unique=True, verbose_name='\u533a\u57df\u540d')),
                ('machine_name', models.CharField(max_length=45, unique=True, verbose_name='\u673a\u623f\u540d')),
                ('remarks', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u521b\u5efa\u7528\u6237')),
                ('update_user', models.CharField(default='now user', editable=False, max_length=30, verbose_name='\u66f4\u65b0\u7528\u6237')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnsuser.DNSUser', to_field='username', verbose_name='\u8d1f\u8d23\u4eba')),
            ],
            options={
                'db_table': 'area',
            },
        ),
    ]
